
name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: YOUR_PROJECT_ID # TODO: update Google Cloud project id
  GAR_LOCATION: YOUR_GAR_LOCATION # TODO: update Artifact Registry location
  SERVICE: YOUR_SERVICE_NAME # TODO: update Cloud Run service name
  REGION: YOUR_SERVICE_REGION # TODO: update Cloud Run service region

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    container: docker:19.03
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build SSH
        run: |-
          cat /etc/os-release
          which ssh-agent || ( apk update && apk add --no-cache openssh && apk add openssh-client git)
          mkdir -p ~/.ssh
          pwd
          echo "NPCI_DEV_SERVER_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          #ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
          apk update && apk add --no-cache python3 py-pip

      

      - name: Build Docker Container
        run: |-
          docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/reposotry/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          
      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
