
name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: YOUR_PROJECT_ID # TODO: update Google Cloud project id
  GAR_LOCATION: YOUR_GAR_LOCATION # TODO: update Artifact Registry location
  SERVICE: YOUR_SERVICE_NAME # TODO: update Cloud Run service name
  REGION: YOUR_SERVICE_REGION # TODO: update Cloud Run service region

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    container: docker:19.03
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build SSH
        run: |-
          cat /etc/os-release
          which ssh-agent || ( apk update && apk add --no-cache openssh && apk add openssh-client git)
          mkdir -p ~/.ssh
          pwd
          echo "NPCI_DEV_SERVER_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          #ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
          apk update && apk add --no-cache python3 py-pip
          
      

      - name: Build Docker Container
        run: |-
          docker build \
          -- docker save --output fn_image.tar frontend:test1 .
          -- echo "$CI_COMMIT_SHA" > fn_tag
          -- scp -o "StrictHostKeyChecking no" fn_image.tar ubuntu@$NPCI_DEV_SERVER:~
          -- scp -o "StrictHostKeyChecking no" deploy_frontend.sh ubuntu@$NPCI_DEV_SERVER:~
          -- scp -o "StrictHostKeyChecking no" fn_tag ubuntu@$NPCI_DEV_SERVER:~
          -- ssh -o "StrictHostKeyChecking no" ubuntu@$NPCI_DEV_SERVER 'chmod +x deploy_frontend.sh; ./deploy_frontend.sh'

          
      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
