
name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: YOUR_PROJECT_ID # TODO: update Google Cloud project id
  GAR_LOCATION: YOUR_GAR_LOCATION # TODO: update Artifact Registry location
  SERVICE: YOUR_SERVICE_NAME # TODO: update Cloud Run service name
  REGION: YOUR_SERVICE_REGION # TODO: update Cloud Run service region

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    container: docker:19.03
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build SSH
        run: |-
          cat /etc/os-release
          which ssh-agent || ( apk update && apk add --no-cache openssh && apk add openssh-client git)
          mkdir -p ~/.ssh
          pwd
          echo "NPCI_DEV_SERVER_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          #ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
          apk update && apk add --no-cache python3 py-pip    
      

      - name: Build Docker image
        run: docker build -t frontend:test1 . 

      - name: Deploy to container     
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.3
        with:
         version: 2  
         
      - name: Publish Docker
        on: [push]
        jobs:
          build:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v3
            - name: Login to gcloud registry
              id: gcloud
              uses: elgohr/gcloud-login-action@v1
              with:
                account_key: ${{ secrets.GCLOUD_KEY }}
            - name: Publish to Registry
              uses: elgohr/Publish-Docker-Github-Action@v4
              with:
                name: myDocker/repository
                username: ${{ steps.gcloud.outputs.username }}
                password: ${{ steps.gcloud.outputs.password }}
                registry: gcr.io, us.gcr.io, eu.gcr.io or asia.gcr.io
